<?php

/**
 * @file
 * Provides common hooks and functions for simple_google_recaptcha module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_form_alter().
 */
function simple_recaptcha_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (\Drupal::currentUser()->hasPermission('bypass simple_recaptcha')) {
    return;
  }

  $config = \Drupal::configFactory()->get('simple_recaptcha.config');

  $form_ids = explode(',', $config->get('form_ids'));
  if (!in_array($form_id, $form_ids)) {
    return;
  }

  $form['#attributes']['data-recaptcha-id'] = $form_id;
  $div_id = $form['#form_id'] . '-captcha';
  // Wrapper for reCAPTCHA widget.
  $form['actions']['captcha']['#markup'] = '<div id="' . $div_id . '" class="recaptcha recaptcha-wrapper"></div>';
  $form['actions']['captcha']['#weight'] = -1;
  // Helper JS.
  $form['#attached']['drupalSettings']['simple_recaptcha']['sitekey'] = $config->get('site_key');
  foreach ($form_ids as $id) {
    $form['#attached']['drupalSettings']['simple_recaptcha']['form_ids'][$id] = $id;
  }
  $form['#attached']['library'][] = 'simple_recaptcha/simple_recaptcha';
  return $form;
}

/**
 * @file
 * This module provides Google reCAPTCHA v2 protection for Drupal forms.
 */

/**
 * Implements hook_help().
 */
function simple_recaptcha_help($route_name, RouteMatchInterface $arg) {
  switch ($route_name) {
    case 'help.page.simple_recaptcha':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This Drupal 8 module provides reCAPTCHA v2 integration, it is crafted to work with different caching strategies, with multiple forms displayed on the same page.') . '</p>';

      // Add a link to the Drupal.org project.
      $output .= '<p>';
      $output .= t('Visit the <a href=":project_link">Simple Google reCaptcha project pages</a> on Drupal.org for more information.', [
        ':project_link' => Url::fromUri('https://www.drupal.org/project/simple_recaptcha')->toString(),
      ]);
      $output .= '</p>';

      return $output;
  }
}
